microsoft/azure-data-services-go-fast-codebase

solution/WebApplication/WebApplication/libman.json

Added the dependencies that were missing from libman.json. Should be able to do a package restore and build and run.

Added missing dependencies to libman.json

---

solution/WebApplication/WebApplication/HelpFiles/ADFActivityErrors.md
solution/WebApplication/WebApplication/HelpFiles/ADFPipelineStats.md
solution/WebApplication/WebApplication/HelpFiles/AFExecutionSummary.md
solution/WebApplication/WebApplication/HelpFiles/AFLogMonitor.md
solution/WebApplication/WebApplication/HelpFiles/Dashboard.md
solution/WebApplication/WebApplication/HelpFiles/DataFactory.md
solution/WebApplication/WebApplication/HelpFiles/FrameworkTaskRunner.md
solution/WebApplication/WebApplication/HelpFiles/Home.md
solution/WebApplication/WebApplication/HelpFiles/ReportsAndStatistics.md
solution/WebApplication/WebApplication/HelpFiles/ScheduleInstance.md
solution/WebApplication/WebApplication/HelpFiles/ScheduleMaster.md
solution/WebApplication/WebApplication/HelpFiles/SourceAndTargetSystems.md
solution/WebApplication/WebApplication/HelpFiles/SourceAndTargetSystemsJsonSchema.md
solution/WebApplication/WebApplication/HelpFiles/SubjectArea.md
solution/WebApplication/WebApplication/HelpFiles/TaskGroup.md
solution/WebApplication/WebApplication/HelpFiles/TaskGroupDependency.md
solution/WebApplication/WebApplication/HelpFiles/TaskInstance.md
solution/WebApplication/WebApplication/HelpFiles/TaskInstanceExecution.md
solution/WebApplication/WebApplication/HelpFiles/TaskMaster.md
solution/WebApplication/WebApplication/HelpFiles/TaskMasterWaterMark.md
solution/WebApplication/WebApplication/HelpFiles/TaskType.md
solution/WebApplication/WebApplication/HelpFiles/TaskTypeMapping.md
solution/WebApplication/WebApplication/Helpers/DefaultHelpLinkActionFilter.cs
solution/WebApplication/WebApplication/Startup.cs
solution/WebApplication/WebApplication/Views/Shared/_Help.cshtml
solution/WebApplication/WebApplication/Views/Shared/_Layout.cshtml
solution/WebApplication/WebApplication/WebApplication.csproj
solution/WebApplication/WebApplication/wwwroot/css/site.css
solution/WebApplication/WebApplication/wwwroot/js/helpSection.js

- Include help slideout on all pages 
- Dynamically render help markdown file if available it based upon convention based `ViewBag.Helplink` value
- added actionfilter to inject default help link based on controller name
- Included some *very* basic help markdown files

Add page help framework

---

solution/WebApplication/WebApplication/libman.json
solution/WebApplication/WebApplication/wwwroot/js/bswindow/bswindow.js

Could not find cdn for bswindow, so I had to manually add it to our js dir

Added missing reference to bswindow

---

solution/Deployment/arm/Networking.json
solution/Deployment/arm/VirtualMachine.json

Moved networking and virtual machine to individual arm templates.

Refactoring ARM template.

---

solution/Deployment/workflows/CI_1a_BuildCode.ps1
solution/FunctionApp/TaskMetaData/TaskInstance.cs

@jrampono FYI fix required to cater for number of records below chunk size.

Fix for chunk batching logic

---

solution/Deployment/environments/development.json
solution/Deployment/environments/environment.schema.json
solution/Deployment/workflows/Steps/CD_DeployStorageADLS.ps1
solution/Deployment/workflows/Steps/CD_GrantRBAC.ps1
solution/Deployment/workflows/Steps/CD_GrantWebAppAccess.ps1
solution/Deployment/workflows/Steps/CD_SetResourceGroupHash.ps1

Deployment of and RBAC on OPTIONAL Transient ADLS Gen2 Storage. Can be Enabled via JSON config.
Closes #29 and #35

Transient ADLS Gen2 Storage

---

solution/Deployment/arm/SynapseWorkspace.json
solution/Deployment/environments/development.json
solution/Deployment/environments/environment.schema.json
solution/Deployment/workflows/Steps/CD_ConfigureAzureMLAccess.ps1
solution/Deployment/workflows/Steps/CD_ConfigureSynapseWorkspace.ps1
solution/Deployment/workflows/Steps/CD_DeploySynapseWorkspace.ps1
solution/Deployment/workflows/Steps/CD_SetResourceGroupHash.ps1

Adding files, changes for Synapse deployment (Managed vNet), Connectivity to ADS GF adls. Also DRAFT of AML Workspace connection configuration.

Adding files, changes for Synapse deployment (Managed vNet), AML

---

solution/WebApplication/WebApplication.DataAccess/Models/TaskMaster.cs
solution/WebApplication/WebApplication/Views/TaskMaster/EditPlus.cshtml

Partially fixed Smart Wizard crashing when a TaskDataFactoryLR was not input.
#66

Add Validation into Task Master EditPlus.cshtml

---

solution/WebApplication/WebApplication/HelpFiles/Wizards/ExternalFileUpload.md

Created a formatted help message for ExternalFileUpload, which describes what ExternalFileUpload is used for.

Added missing help file.

---

solution/WebApplication/WebApplication/wwwroot/js/site.js

DataTable saves which table page you are on as well as the selection when moving to and from pages.
#52

Row Selection

---

solution/WebApplication/WebApplication/Models/Options/DependencyOptions.cs
solution/WebApplication/WebApplication/Startup.cs
solution/WebApplication/WebApplication/appsettings.json
solution/WebApplication/WebApplication/readme.md

Startup.cs has a check for ConnectionString in appsettings.json under the "ApplicationSettings". To make it easier to locally run the project.

Created A Check For ConnectionString

---

solution/WebApplication/WebApplication/wwwroot/js/site.js

Fixed an issue where the datatables all shared the same name in the localstorage, resulting in the selection being saved across to different tables.

Fixed Table Data being saved to a different pages table.

---

solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/012-ConfigureDependencies.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/013-CreateMSILogins.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/AdsGoFastDbUp.csproj
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/AdsGoFastDbUp.sln
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/AzureSqlConnectionManager.cs
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/AzureSqlServerExtensions.cs
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/Program.cs
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/Properties/launchSettings.json

*   Replaced the legacy AppService auth with Microsoft.Identity.Web. This allows us to leverage the Az Cli auth both locally and on github.
*   Now creates the MSI logins as well
*   Updates all the dependencies using parameters (this means one less script to have to run later in the Deployment pipelines)

Update the DB up tool to allow for parameterisation and better auth

---

.devcontainer/.gitattributes
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/azcli-debian.sh
.devcontainer/library-scripts/common-debian.sh

*   Moved the ./.devcontainer/ folder into the repo root so that VSCode/codespaces will work with it better.
*   Moved the postCreate commands into the dockerfile image build.
*   This should mean we do the expensive dependency install commands once when the docker image is build rather than each time a container is created. Should mean faster average container attach times when the container gets destroyed/recreated.
*   Added dependencies terraform / terragrunt for DeploymentV2 support
*   Added devcontainer vscode extensions to improved the outofthebox editor experience for dev containers

Updated dev container to support TF

---

.github/workflows/build-component.yml
.github/workflows/continuous-delivery.yml
.github/workflows/publish-component.yml
.github/workflows/pull-request.yml

Added GitHub workflows/actions for CI/CD using Deployment V2 (terraform). This includes a PR workflow and a Continuous Delivery workflow. 
The PR workflow will:
*   Build and test all of the applications (web, function, dbup)
*   Note that we use templates and they are currently referencing (microsoft/azure-data-services-go-fast-codebase/.github/workflows/publish-component.yml@task/main.
*   This means that these wont work until the PR is merged and these reusable templates are in the main branch.
The continuous delivery workflow will:
*   Publish packages for all deployable components (web, function, dbup)
*   Deploy to multiple environments (staging & prod)
*   Support github environments features
*   Support gated approvals on environments
*   Read all configuration from GitHub …

Added github workflows for deployment V2

---

.github/workflows/continuous-delivery.yml
solution/DeploymentV2/Deploy.ps1
solution/DeploymentV2/Prepare.ps1
solution/DeploymentV2/terraform/.gitignore
solution/DeploymentV2/terraform/vars/local/terragrunt.hcl
solution/DeploymentV2/terraform/vars/production/terragrunt.hcl

*   Fixed all references to /Deployment/ path
*   Fixed nested template references
*   Cleaned up terragrunt sample files to remove arkahna references.

Fixed GitHub actions and Deploy scripts

---

.github/workflows/continuous-delivery.yml
solution/DeploymentV2/Deploy.ps1
solution/DeploymentV2/Prepare.ps1
solution/DeploymentV2/terraform/.gitignore
solution/DeploymentV2/terraform/.terraform.lock.hcl
solution/DeploymentV2/terraform/security.tf
solution/DeploymentV2/terraform/vars.tf
solution/DeploymentV2/terraform/vars/local/terragrunt.hcl
solution/DeploymentV2/terraform/vars/production/terragrunt.hcl
solution/DeploymentV2/terraform/vars/staging/terragrunt.hcl

*   Registered the required Azure resource provider within the Prepare.ps1
*   Added sentinel workspace registration on the Log Analytics workspace
*   Feature toggle to disable sentinel deployment (Sentinel is off by default)

Added Azure sentinel support to lockbox (Merge PR 121 first)

---

.github/workflows/continuous-delivery.yml
solution/DeploymentV2/terraform/app_service.tf
solution/DeploymentV2/terraform/function_app.tf
solution/DeploymentV2/terraform/locals.tf
solution/DeploymentV2/terraform/vars/staging/terragrunt.hcl

*   Updating the AAD app registration details to be uniqueto use default identifierUri format 
*   generate unique id for roles.
*   Added missing param to the CI'CD pipeline

Updating the AAD app registration details to be unique

---

solution/DataFactory/Patterns/Jsonnet_GenerateADFArtefacts.ps1
solution/DataFactory/Patterns/Patterns.json
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobFS_DelimitedText_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobFS_Excel_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobFS_Json_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobStorage_DelimitedText_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobStorage_Excel_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobStorage_Json_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureSqlTable_NA_Outputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_AutoMergeSQL_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_CreateStage_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_CreateTarget_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_MergeSQL_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_PostCopySQL_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/static/AZ_Function_Generic.json

John, here are the changes I made to your templates so that:
*    They generate valid ARM templates
*   The ARM templates are parameterisable by IR (allows us to create dynamic IRs from terraform)
This also includes the template for AZ Storage to AZ Storage

Leigh's WIP for John: ARM template based patterns

---

solution/DataFactory/Patterns/Jsonnet_GenerateADFArtefacts.ps1
solution/DataFactory/Patterns/Patterns.json
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobFS_DelimitedText_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobFS_Excel_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobFS_Json_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobStorage_DelimitedText_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobStorage_Excel_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureBlobStorage_Json_Inputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_AzureSqlTable_NA_Outputs.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Main_CopyActivity_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_AutoMergeSQL_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_CreateStage_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_CreateTarget_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_MergeSQL_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/Azure-Storage-to-SQL-Database/partials/Post_Copy_Lookup_PostCopySQL_TypeProperties.libsonnet
solution/DataFactory/Patterns/pipeline/static/AZ_Function_Generic.json

Reverts microsoft/azure-data-services-go-fast-codebase#127

Revert "Leigh's WIP for John: ARM template based patterns"

---

solution/WebApplication/WebApplication.DataAccess/Models/SubjectArea.cs
solution/WebApplication/WebApplication/Controllers/SubjectAreaController.cs
solution/WebApplication/WebApplication/Views/SubjectArea/Create.cshtml
solution/WebApplication/WebApplication/Views/SubjectArea/Edit.cshtml

Change model to allow for validation.
Commented out SubjectFormId as it was not used.

Validation Checking For Subject Area Create

---

solution/WebApplication/WebApplication.DataAccess/Models/TaskMasterWaterMark.cs
solution/WebApplication/WebApplication/Views/TaskMasterWaterMark/Create.cshtml
solution/WebApplication/WebApplication/Views/TaskMasterWaterMark/Edit.cshtml

Changed model to allow validation.
Removed UpdatedOn as it shouldn't be changeable.

Validation Checking For TaskMasterWaterMark Create

---

solution/WebApplication/WebApplication/Controllers/TaskMasterWaterMarkController.cs

Dropdown and Autoselect now displays the correct information.
#100

Enhance Watermark Forms

---

solution/WebApplication/WebApplication/Controllers/TaskMasterWaterMarkController.cs
solution/WebApplication/WebApplication/Views/TaskMasterWaterMark/Create.cshtml
solution/WebApplication/WebApplication/Views/TaskMasterWaterMark/Edit.cshtml

A Hidden returnUrl has been added to handle going back to the page you came from when finished editing/creating.
Depends on the changes in PR #129 & #128
#52

Watermark Forms Now Save A ReturnUrl

---

solution/WebApplication/WebApplication/Controllers/TaskGroupController.cs
solution/WebApplication/WebApplication/Views/TaskGroup/Create.cshtml
solution/WebApplication/WebApplication/Views/TaskGroup/Edit.cshtml

A Hidden returnUrl has been added to handle going back to the page you came from when finished editing/creating.
#52

TaskGroup Forms Now Saves A ReturnUrl

---

solution/WebApplication/WebApplication/Controllers/SourceAndTargetSystemsController.cs
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Create.cshtml
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Edit.cshtml

Converted Input SystemAuthType to Select SystemAuthType to allow easier selection.
Created a function to generate the list for the dropdown

Dropdown for SystemAuthType

---

solution/WebApplication/WebApplication.DataAccess/Models/FrameworkTaskRunner.cs

Created validation for framworktaskrunner

Validation Check FrameworkTaskRunner

---

solution/WebApplication/WebApplication.DataAccess/Models/SourceAndTargetSystemsJsonSchema.cs

Created validation for Source And Target Json Schema

Validation Check Source And Target Json Schema

---

solution/WebApplication/WebApplication.DataAccess/Models/DataFactory.cs

Created validation for DataFactory

Validation Check Data Factory

---

solution/WebApplication/WebApplication.DataAccess/Models/ScheduleMaster.cs

Created validation for Schedule Master

Validation Check Schedule Master

---

solution/WebApplication/WebApplication.DataAccess/Models/TaskGroup.cs

Created validation for Task Group

Validation Check Task Group

---

solution/WebApplication/WebApplication.DataAccess/Models/TaskGroupDependency.cs

Created validation for Task Group Dependency

Validation Check Task Group Dependency

---

solution/WebApplication/WebApplication.DataAccess/Models/TaskType.cs

Created a validation for Task Type

Validation Check Task Type

---

solution/WebApplication/WebApplication.DataAccess/Models/TaskTypeMapping.cs

Created validation for Task Type Mapping

Validation Check Task Type Mapping

---

solution/DeploymentV2/terraform/function_app.tf
solution/DeploymentV2/terraform/key_vault.tf
solution/DeploymentV2/terraform/purview.tf
solution/DeploymentV2/terraform/synapse.tf

Fixed dependencies, removed obsolete RBAC role for purview.

Fixed dependencies in TF

---

solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/002-Tables.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/008-SampleTasks_SourceAndTargetSystems.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/015-UpdateSourceAndTargetSystems.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/020-UpdateSourceAndTargetSystems.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/AdsGoFastDbUp.csproj
solution/WebApplication/WebApplication.DataAccess/Models/AdsGoFastContext.cs
solution/WebApplication/WebApplication.DataAccess/Models/SourceAndTargetSystems.cs
solution/WebApplication/WebApplication/Controllers/SourceAndTargetSystemsController.cs
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Create.cshtml
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Details.cshtml
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Edit.cshtml
solution/WebApplication/WebApplication/Views/TaskMaster/EditPlus.cshtml
solution/WebApplication/WebApplication/wwwroot/js/TaskMasterEditPlus.js

---
- SQL Table SourceandTargetSystems now has a column for "IsExternal"
- SQL Sample Data for SourceandTargetSystems has been updated to work with this change in the table. (Will need to rebuild Database)
- Created 2 new Samples for SourceandTargetSystems where "IsExternal" has been set to True (1)
- An **ALTER TABLE** script has been created. Probably better to rebuild the entire database so you don't run into errors when running the Webapp
- AdsGoFastContext.cs has been updated to allow the use of "IsExternal"
- Creating or Editing a SourceandTargetSystem now displays a checkbox for IsExternal
- Created 2 new functions in TaskMasterEditPlus.js to display **Warning Messages** for Source and Target systems when IsExternal is set to True
---

Created Check For Is External

---

solution/DeploymentV2/terraform/function_app.tf
solution/DeploymentV2/terraform/key_vault.tf

Added some additional comments regarind the KV access as well.

Remove direct secret use and replace with KeyVault

---

solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/002-Tables.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/008-SampleTasks_SourceAndTargetSystems.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/015-UpdateSourceAndTargetSystems.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/0-1-0-beta/A-Journaled/020-UpdateSourceAndTargetSystems.sql
solution/Database/ADSGoFastDbUp/AdsGoFastDbUp/AdsGoFastDbUp.csproj
solution/WebApplication/WebApplication.DataAccess/Models/AdsGoFastContext.cs
solution/WebApplication/WebApplication.DataAccess/Models/SourceAndTargetSystems.cs
solution/WebApplication/WebApplication/Controllers/SourceAndTargetSystemsController.cs
solution/WebApplication/WebApplication/Controllers/TaskTypeMappingController.cs
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Create.cshtml
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Details.cshtml
solution/WebApplication/WebApplication/Views/SourceAndTargetSystems/Edit.cshtml
solution/WebApplication/WebApplication/Views/TaskMaster/EditPlus.cshtml
solution/WebApplication/WebApplication/wwwroot/js/TaskMasterEditPlus.js

Errors when selecting a Task Type that has no values inside it will show a toast notification and reset the wizard instead of showing every single source and target type.
Has all the commits from #159 built into it.

Created a toast nofication for errors 
